#!/bin/sh

sudo apt update
sudo apt -y upgrade
sudo apt -y dist-upgrade

sudo apt -y install python-software-properties software-properties-common \
    gcc make build-essential libssl-dev libffi-dev python-dev \
    git-core tmux python3 python python-pip python3-dev python3-pip ssh zsh xclip xsel \
    libevent-dev libncurses-dev pkg-config \
    autotools-dev automake cscope vim tree

# Make vi an alias to vim
sudo update-alternatives --install /usr/bin/vi vi /usr/bin/vim 60
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/vim 60

sudo apt autoremove
sudo apt autoclean

if [ -e ~/.fzf ]; then
  rm -fr ~/.fzf
fi

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --no-update-rc --64 --key-bindings --completion

if [ -e ~/.tmux ]; then
  rm -fr ~/.tmux
fi

# Clone tmux from git
git clone https://github.com/tmux/tmux.git ~/.tmux
cd ~/.tmux
./autogen.sh
./configure
make -j 12
sudo make install
