-- local status_ok, self = pcall(require, "nvim-highlight-colors")
-- if not status_ok then
-- 	return
-- end
--
-- self.setup({
--   toggler = {
--     line = "<C-/>",
--     block = "<C-?>",
--   },
--   opleader = {
--     line = "<C-/>",
--     block = "<C-?>",
--   },
-- })
