-- local status_ok, jdtls = pcall(require, "jdtls")
-- if not status_ok then
--   return
-- end
--
-- local nvim_jdtls_group = vim.api.nvim_create_augroup("nvim-jdtls", { clear = true })
-- vim.api.nvim_create_autocmd("FileType", {
--   -- NOTE: You may or may not want java included here. You will need it if you
--   -- want basic Java support but it may also conflict if you are using
--   -- something like jdtls which also works on a java filetype autocmd.
--   pattern = { "java" },
--   callback = function()
--     local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')
--
--     local workspace_dir = vim.fn.expand('$HOME/code/' .. project_name)
--
--     local config = {
--       cmd = {
--
--         -- 💀
--         'java', -- or '/path/to/java17_or_newer/bin/java'
--         -- depends on if `java` is in your $PATH env variable and if it points to the right version.
--
--         '-Declipse.application=org.eclipse.jdt.ls.core.id1',
--         '-Dosgi.bundles.defaultStartLevel=4',
--         '-Declipse.product=org.eclipse.jdt.ls.core.product',
--         '-Dlog.protocol=true',
--         '-Dlog.level=ALL',
--         '-Xmx1g',
--         '--add-modules=ALL-SYSTEM',
--         '--add-opens', 'java.base/java.util=ALL-UNNAMED',
--         '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
--
--         -- 💀
--         '-jar', vim.fn.expand('$HOME/jdt-language-server-1.36.0-202405301306/plugins/org.eclipse.equinox.launcher_1.6.800.v20240513-1750.jar'),
--
--
--         -- 💀
--         '-configuration', vim.fn.expand('$HOME/jdt-language-server-1.36.0-202405301306/config_mac_arm'),
--
--         -- 💀
--         -- See `data directory configuration` section in the README
--         '-data', '/path/to/unique/per/project/workspace/folder'
--       },
--
--       filetypes = {"java"},
--       root_dir = vim.fs.root(0, {".git", "mvnw", "gradlew", 'pom.xml'}),
--
--       settings = {
--         java = {
--         }
--       },
--
--       init_options = {
--         bundles = {}
--       },
--     }
--
--
--     jdtls.start_or_attach(config)
--   end,
--   group = nvim_jdtls_group,
-- })
