name: Generate docs and format

on:
  push:
    branches:
      - master
  pull_request:
    types: 
      - synchronize

jobs:
  postprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: luasnip
          pandoc: DOC.md

      - uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: "Auto generate docs"
      - name: "Format with Stylua"
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format with stylua"
